sudo: false

language: node_js

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.24.1

node_js:
  - "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.2

script:
  - yarn test

notifications:
  email: false
